flashcard[23] = {

AL = {"Bradley Byrne"}
AK = {"Don Young"}
AZ = {"Martha McSally"}
AR = {"French Hill"}
CA = {"Jared Huffman"}
CO = {"Ken Buck"}
CT = {"Elizabeth Esty"}
DE = {"John Carney"}
FL = {"Ted Yoho"}
GA = {"Buddy Carter"}
HI = {"Mark Takai"}
ID = {"Raúl Labrador"}
IL = {"Robert Dold"}
IN = {"Susan Brooks"}
IA = {"Rod Blum"}
KS = {"Mike Pompeo"}
KY = {"Andy Barr"}
LA = {"Ralph Abraham"}
ME = {"Bruce Poliquin"}
MD = {"John Delaney"}
MA = {"Joe Kennedy"}
MI = {"John Moolenaar"}
MN = {"Tom Emmer"}
MS = {"Trent Kelly"}
MO = {"Ann Wagner"}
MT = {"Ryan Zinke"}
NE = {"Brad Ashford"}
NV = {"Dina Titus"}
NH = {"Frank Guinta"}
NJ = {"Tom MacArthur"}
NM = {"Steve Pearce"}
NY = {"Lee Zeldin"}
NC = {"Mark Walker"}
ND = {"Kevin Cramer"}
OH = {"Bill Johnson"}
OK = {"Steve Russell"}
OR = {"Kurt Schrader"}
PA = {"Scott Perry"}
RI = {"David Cicilline"}
SC = {"Jeff Duncan"}
SD = {"Kristi Noem"}
TN = {"Diane Black"}
TX = {"John Ratcliffe"}
UT = {"Chris Stewart"}
VT = {"Peter Welch"}
VA = {"Scott Rigell"}
WA = {"Jaime Herrera Beutler"}
WV = {"Alex Mooney"}
WI = {"Mark Pocan"}
WY = {"Cynthia Lummis"}

}

flashcard[43] = {

AL	 =	{"	Robert Bentley	"}	
AK	 =	{"	Bill Walker	"}	,
AZ	 =	{"	Doug Ducey	"}	,
AR	 =	{"	Asa Hutchinson	"}	,
CA	 =	{"	Jerry Brown	"}	,
CO	 =	{"	John Hickenlooper	"}	,
CT	 =	{"	Dannel Malloy	"}	,
DE	 =	{"	Jack Markell	"}	,
FL	 =	{"	Rick Scott	"}	,
GA	 =	{"	Nathan Deal	"}	,
HI	 =	{"	David Ige	"}	,
ID	 =	{"	Butch Otter	"}	,
IL	 =	{"	Bruce Rauner	"}	,
IN	 =	{"	Mike Pence	"}	,
IA	 =	{"	Terry Branstad	"}	,
KS	 =	{"	Sam Brownback	"}	,
KY	 =	{"	Steve Beshear	"}	,
LA	 =	{"	Bobby Jindal	"}	,
ME	 =	{"	Paul LePage	"}	,
MD	 =	{"	Larry Hogan	"}	,
MA	 =	{"	Charlie Baker	"}	,
MI	 =	{"	Rick Snyder	"}	,
MN	 =	{"	Mark Dayton	"}	,
MS	 =	{"	Phil Bryant	"}	,
MO	 =	{"	Jay Nixon	"}	,
MT	 =	{"	Steve Bullock	"}	,
NE	 =	{"	Pete Ricketts	"}	,
NV	 =	{"	Brian Sandoval	"}	,
NH	 =	{"	Maggie Hassan	"}	,
NJ	 =	{"	Chris Christie	"}	,
NM	 =	{"	Susana Martinez	"}	,
NY	 =	{"	Andrew Cuomo	"}	,
NC	 =	{"	Pat McCrory	"}	,
ND	 =	{"	Jack Dalrymple	"}	,
OH	 =	{"	John Kasich	"}	,
OK	 =	{"	Mary Fallin	"}	,
OR	 =	{"	Kate Brown	"}	,
PA	 =	{"	Tom Wolf	"}	,
RI	 =	{"	Gina Raimondo	"}	,
SC	 =	{"	Nikki Haley	"}	,
SD	 =	{"	Dennis Daugaard	"}	,
TN	 =	{"	Bill Haslam	"}	,
TX	 =	{"	Greg Abbott	"}	,
UT	 =	{"	Gary Herbert	"}	,
VT	 =	{"	Peter Shumlin	"}	,
VA	 =	{"	Terry McAuliffe	"}	,
WA	 =	{"	Jay Inslee	"}	,
WV	 =	{"	Earl Ray Tomblin	"}	,
WI	 =	{"	Scott Walker	"}	,
WY	 =	{"	Matt Mead	"}	



}

flashcard[44] = {

AL = {""},
AK = {""},
AZ = {""},
AR = {""},
CA = {""},
CO = {""},
CT = {""},
DE = {""},
FL = {""},
GA = {""},
HI = {""},
ID = {""},
IL = {""},
IN = {""},
IA = {""},
KS = {""},
KY = {""},
LA = {""},
ME = {""},
MD = {""},
MA = {""},
MI = {""},
MN = {""},
MS = {""},
MO = {""},
MT = {""},
NE = {""},
NV = {""},
NH = {""},
NJ = {""},
NM = {""},
NY = {""},
NC = {""},
ND = {""},
OH = {""},
OK = {""},
OR = {""},
PA = {""},
RI = {""},
SC = {""},
SD = {""},
TN = {""},
TX = {""},
UT = {""},
VT = {""},
VA = {""},
WA = {""},
WV = {""},
WI = {""},
WY = {""}

}

